name: BORRACHO
favicon: null
layout_spectrum: 0.17322
typography_spectrum: 1
title: BORRACHO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0dccd'
    - '#6a6356'
    - '#aaa899'
    - '#313129'
    - '#9c8a7d'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
